# -*- coding: utf-8 -*-
"""RL traffic control.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UF-G1nsApQb_eySGylhKve0mZw3xKVQs
"""

!pip install stable-baselines3 gymnasium matplotlib pygame

import gymnasium as gym
from gymnasium import spaces
import numpy as np
import random
import pygame
import matplotlib.pyplot as plt
from stable_baselines3 import PPO

# ================================
# VISUAL TRAFFIC ENVIRONMENT
# ================================

class TrafficEnv(gym.Env):
    def __init__(self):
        super(TrafficEnv, self).__init__()

        self.observation_space = spaces.Box(low=0, high=50, shape=(4,), dtype=np.float32)
        self.action_space = spaces.Discrete(2)

        self.state = None
        self.max_steps = 50
        self.current_step = 0

        # Initialize pygame
        pygame.init()
        self.screen = pygame.display.set_mode((400, 400))
        pygame.display.set_caption("Smart Traffic AI")

    def reset(self, seed=None, options=None):
        super().reset(seed=seed)
        self.state = np.random.randint(0, 20, size=(4,))
        self.current_step = 0
        return self.state.astype(np.float32), {}

    def step(self, action):
        if action == 0:
            self.state[0] = max(0, self.state[0] - random.randint(2, 6))
            self.state[1] = max(0, self.state[1] - random.randint(2, 6))
        else:
            self.state[2] = max(0, self.state[2] - random.randint(2, 6))
            self.state[3] = max(0, self.state[3] - random.randint(2, 6))

        self.state += np.random.randint(0, 4, size=(4,))

        # Improved reward
        waiting_penalty = np.sum(self.state)
        balance_penalty = abs((self.state[0]+self.state[1]) - (self.state[2]+self.state[3]))

        reward = -(waiting_penalty + 0.5 * balance_penalty)

        self.current_step += 1
        terminated = self.current_step >= self.max_steps
        truncated = False

        return self.state.astype(np.float32), reward, terminated, truncated, {}

    def render(self):
        self.screen.fill((0, 0, 0))

        # Draw roads
        pygame.draw.rect(self.screen, (50, 50, 50), (150, 0, 100, 400))
        pygame.draw.rect(self.screen, (50, 50, 50), (0, 150, 400, 100))

        # Draw cars (circles)
        for i in range(self.state[0]):
            pygame.draw.circle(self.screen, (255, 0, 0), (180, 20 + i*5), 3)
        for i in range(self.state[1]):
            pygame.draw.circle(self.screen, (255, 0, 0), (220, 380 - i*5), 3)
        for i in range(self.state[2]):
            pygame.draw.circle(self.screen, (0, 255, 0), (20 + i*5, 180), 3)
        for i in range(self.state[3]):
            pygame.draw.circle(self.screen, (0, 255, 0), (380 - i*5, 220), 3)

        pygame.display.flip()


# ================================
# TRAIN MODEL
# ================================

env = TrafficEnv()
model = PPO("MlpPolicy", env, verbose=1)

print("Training...")
model.learn(total_timesteps=15000)

# ================================
# TEST WITH VISUALIZATION
# ================================

obs, _ = env.reset()
rewards = []

for _ in range(100):
    action, _ = model.predict(obs)
    obs, reward, done, _, _ = env.step(action)
    rewards.append(reward)

    env.render()
    pygame.time.delay(200)

    if done:
        break

pygame.quit()

# ================================
# GRAPH
# ================================

plt.plot(rewards)
plt.title("Reward Trend (Advanced Model)")
plt.xlabel("Steps")
plt.ylabel("Reward")
plt.show()